-- Generated from generator/demo_specs/aws-vietnam-renewable-carbon.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-renewable-carbon
-- This is the schema that is actually deployed for VIETNAM_RENEWABLE_CARBON.

-- Alerts fire on the bottom tail of Avg Price
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_PRICE) AS T
  FROM RAW.CREDIT_ISSUANCES
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_PRICE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_PRICE), 2) AS AVG_PRICE,
  ROUND(AVG(f.KPI_VCM_PRICE_TREND), 2) AS AVG_VCM_PRICE_TREND,
  ROUND(AVG(f.KPI_COMPLIANCE_DEMAND), 2) AS AVG_COMPLIANCE_DEMAND,
  ROUND(AVG(f.KPI_RETIREMENT_RATE), 2) AS AVG_RETIREMENT_RATE
FROM RAW.CREDIT_ISSUANCES f
JOIN RAW.CARBON_PROJECTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_PRICE), 2) AS AVG_PRICE,
  ROUND(AVG(f.KPI_VCM_PRICE_TREND), 2) AS AVG_VCM_PRICE_TREND,
  ROUND(AVG(f.KPI_COMPLIANCE_DEMAND), 2) AS AVG_COMPLIANCE_DEMAND,
  ROUND(AVG(f.KPI_RETIREMENT_RATE), 2) AS AVG_RETIREMENT_RATE
FROM RAW.CREDIT_ISSUANCES f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_AVG_PRICE) AS KPI_AVG_PRICE, AVG(KPI_VCM_PRICE_TREND) AS KPI_VCM_PRICE_TREND, AVG(KPI_COMPLIANCE_DEMAND) AS KPI_COMPLIANCE_DEMAND, AVG(KPI_RETIREMENT_RATE) AS KPI_RETIREMENT_RATE FROM RAW.CREDIT_ISSUANCES),
     en AS (SELECT SUM(KPI_CARBON_CREDITS_ISSUED) AS KPI_CARBON_CREDITS_ISSUED, SUM(KPI_PROJECTS_ACTIVE) AS KPI_PROJECTS_ACTIVE, SUM(KPI_REVENUE_YTD) AS KPI_REVENUE_YTD FROM RAW.CARBON_PROJECTS)
  SELECT 1 AS SORT_ORDER, 'Carbon Credits Issued' AS TITLE, KPI_CARBON_CREDITS_ISSUED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_CARBON_CREDITS_ISSUED) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'tCO2e' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Avg Price' AS TITLE, KPI_AVG_PRICE AS VALUE_NUM, '₫' || TO_VARCHAR(CAST(ROUND(((KPI_AVG_PRICE) / 1000)) AS DECIMAL(38,0))) || 'K' || '/tCO2e' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Projects Active' AS TITLE, KPI_PROJECTS_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PROJECTS_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Revenue (YTD)' AS TITLE, KPI_REVENUE_YTD AS VALUE_NUM, '₫' || TO_VARCHAR(CAST(ROUND(((KPI_REVENUE_YTD) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'VCM Price Trend' AS TITLE, KPI_VCM_PRICE_TREND AS VALUE_NUM, '↑' || ' ' || TO_VARCHAR(CAST(ROUND((KPI_VCM_PRICE_TREND)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Compliance Demand' AS TITLE, KPI_COMPLIANCE_DEMAND AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_COMPLIANCE_DEMAND)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Retirement Rate' AS TITLE, KPI_RETIREMENT_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RETIREMENT_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
