-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Carbon Credit Trading
-- ============================================================================
USE DATABASE CARBON_TRADING;
USE SCHEMA ML;

-- ML.FORECAST: CARBON_TRADING_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CARBON_TRADING_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FORECAST_INPUT'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.CARBON_TRADING_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.CARBON_TRADING_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: CARBON_TRADING_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.CARBON_TRADING_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.CARBON_TRADING_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.CARBON_TRADING_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'), SERIES_COLNAME => 'ENTITY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

